[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coolerspace"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = ["onnx", "networkx", "numpy"]
readme="readme.md"